{{- if .Values.rolloutrestart.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sharedconfig.rolloutrestart.serviceAccountName" . }}
  labels:
    {{- include "sharedconfig.labels" . | nindent 4 }}
  {{- with .Values.rolloutrestart.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
